name       : matplotlib
version    : 1.5.0
release    : 6
source     :
    - https://pypi.python.org/packages/source/m/matplotlib/matplotlib-1.5.0.tar.gz : 67b08b1650a00a6317d94b76a30a47320087e5244920604c5462188cba0c2646
license    : Python-2.0
summary    : Python plotting library
description: |
    matplotlib strives to produce publication quality 2D graphics for interactive graphing, scientific publishing, user interface development and web application servers targeting multiple user interfaces and hardcopy output formats. There is a ‘pylab’ mode which emulates matlab graphics.
builddeps  :
    - pkgconfig(python-3.5)
    - pkgconfig(python-2.7)
    - pkgconfig(libpng)
    - numpy
rundeps    :
    - numpy
    - pyparsing
    - cycler
    - python-dateutil
    - python-six
build      : |
    for py in "python2" "python3.5"; do
        ${py} setup.py build
    done
install    : |
    for py in "python2" "python3.5"; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
