name       : matplotlib
version    : 2.0.0
release    : 8
source     :
    - https://github.com/matplotlib/matplotlib/archive/v2.0.0.tar.gz : 966a0807bc961726a68e5b60b6e97c91eed6ba20e0d50dfd699a8f854b2d7370
license    : Python-2.0
component  : programming.python
summary    : Python plotting library
description: |
    matplotlib strives to produce publication quality 2D graphics for interactive graphing, scientific publishing, user interface development and web application servers targeting multiple user interfaces and hardcopy output formats. There is a ‘pylab’ mode which emulates matlab graphics.
builddeps  :
    - pkgconfig(python-3.5)
    - pkgconfig(python-2.7)
    - pkgconfig(libpng)
    - pkgconfig(tk)
    - pkgconfig(x11)
    - numpy
    - python-setuptools
    - python-tkinter
    - python3-tkinter
rundeps    :
    - numpy
    - pyparsing
    - cycler
    - python-dateutil
    - python-functools32
    - python-six
    - python-tkinter
    - python3-tkinter
build      : |
    export CFLAGS="$CFLAGS -I/usr/include"
    for py in "python2" "python3.5"; do
        ${py} setup.py build
    done
install    : |
    for py in "python2" "python3.5"; do
        ${py} setup.py install --root=%installroot%
    done
