name       : matplotlib
version    : 2.1.0
release    : 11
source     :
    - https://github.com/matplotlib/matplotlib/archive/v2.1.0.tar.gz : e0cd1ee9593ec1c85e8b3f210824ff563fad0c55fbeccfeed0742c8dd27f2c56
license    : Python-2.0
component  : programming.python
summary    : Python plotting library
description: |
    matplotlib strives to produce publication quality 2D graphics for interactive graphing, scientific publishing, user interface development and web application servers targeting multiple user interfaces and hardcopy output formats. There is a ‘pylab’ mode which emulates matlab graphics.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(libpng)
    - pkgconfig(python-3.5)
    - pkgconfig(tk)
    - pkgconfig(x11)
    - numpy
    - python-setuptools
    - python-tkinter
    - python3-tkinter
rundeps    :
    - cycler
    - numpy
    - pyparsing
    - python-dateutil
    - python-functools32
    - python-pytz
    - python-six
    - python-subprocess32
    - python-tkinter
    - python3-tkinter
build      : |
    export CFLAGS="$CFLAGS -I/usr/include"
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
