name       : matplotlib
version    : 2.2.0
release    : 15
source     :
    - https://github.com/matplotlib/matplotlib/archive/v2.2.0.tar.gz : b1dfd2bec5fae524469a046b3d9083772fb41c547a581b2bdf84f017b7649eff
license    : Python-2.0
component  : programming.python
summary    : Python plotting library
description: |
    matplotlib strives to produce publication quality 2D graphics for interactive graphing, scientific publishing, user interface development and web application servers targeting multiple user interfaces and hardcopy output formats. There is a ‘pylab’ mode which emulates matlab graphics.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(libpng)
    - pkgconfig(python3)
    - pkgconfig(tk)
    - pkgconfig(x11)
    - numpy
    - python-setuptools
    - python-tkinter
    - python3-tkinter
rundeps    :
    - cycler
    - numpy
    - pyparsing
    - python-backports.functools_lru_cache
    - python-dateutil
    - python-kiwisolver
    - python-pytz
    - python-six
    - python-subprocess32
    - python-tkinter
    - python3-tkinter
build      : |
    export CFLAGS="$CFLAGS -I/usr/include"
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
