name       : matplotlib
version    : 2.0.1
release    : 9
source     :
    - https://github.com/matplotlib/matplotlib/archive/v2.0.1.tar.gz : 817c873084830a9169115e94a54ae6e7ef4f7b54d334a4ed0a63fac29393faa4
license    : Python-2.0
component  : programming.python
summary    : Python plotting library
description: |
    matplotlib strives to produce publication quality 2D graphics for interactive graphing, scientific publishing, user interface development and web application servers targeting multiple user interfaces and hardcopy output formats. There is a ‘pylab’ mode which emulates matlab graphics.
builddeps  :
    - pkgconfig(python-3.5)
    - pkgconfig(python-2.7)
    - pkgconfig(libpng)
    - pkgconfig(tk)
    - pkgconfig(x11)
    - numpy
    - python-setuptools
    - python-tkinter
    - python3-tkinter
rundeps    :
    - numpy
    - pyparsing
    - cycler
    - python-dateutil
    - python-functools32
    - python-six
    - python-tkinter
    - python3-tkinter
build      : |
    export CFLAGS="$CFLAGS -I/usr/include"
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
