name       : matplotlib
version    : 3.4.3
release    : 25
source     :
    - https://github.com/matplotlib/matplotlib/archive/refs/tags/v3.4.3.tar.gz : 474c4c5555476eb35f44cfd00a4c9b7b24fff9cef685ec80e52260cc33558b0c
homepage   : https://matplotlib.org/
license    : Python-2.0
component  : programming.python
summary    : Python plotting library
description: |
    matplotlib strives to produce publication quality 2D graphics for interactive graphing, scientific publishing, user interface development and web application servers targeting multiple user interfaces and hardcopy output formats. There is a ‘pylab’ mode which emulates matlab graphics.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(python3)
    - pkgconfig(qhull_r)
    - pkgconfig(tk)
    - pkgconfig(x11)
    - numpy
    - python-certifi
    - python3-tkinter
rundeps    :
    - cycler
    - numpy
    - pyparsing
    - python-dateutil
    - python-kiwisolver
    - python-pillow
    - python-pytz
    - python3-tkinter
setup      : |
    # Use system freetype
    sed -e 's|#system_freetype = False|system_freetype = True|' -e 's|#system_qhull = False|system_qhull = True|' setup.cfg.template > setup.cfg
build      : |
    export CFLAGS="$CFLAGS -I/usr/include"
    %python3_setup
install    : |
    %python3_install
