name       : matplotlib
version    : 2.1.1
release    : 12
source     :
    - https://github.com/matplotlib/matplotlib/archive/v2.1.1.tar.gz : 40830d614384f0d837c81f1ca3cef795cfb871cb1d49cde0fc5beea157cec372
license    : Python-2.0
component  : programming.python
summary    : Python plotting library
description: |
    matplotlib strives to produce publication quality 2D graphics for interactive graphing, scientific publishing, user interface development and web application servers targeting multiple user interfaces and hardcopy output formats. There is a ‘pylab’ mode which emulates matlab graphics.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(libpng)
    - pkgconfig(python-3.5)
    - pkgconfig(tk)
    - pkgconfig(x11)
    - numpy
    - python-setuptools
    - python-tkinter
    - python3-tkinter
rundeps    :
    - cycler
    - numpy
    - pyparsing
    - python-backports.functools_lru_cache
    - python-dateutil
    - python-pytz
    - python-six
    - python-subprocess32
    - python-tkinter
    - python3-tkinter
build      : |
    export CFLAGS="$CFLAGS -I/usr/include"
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
