name       : matplotlib
version    : 3.3.4
release    : 20
source     :
    - https://github.com/matplotlib/matplotlib/archive/v3.3.4.tar.gz : ce7cebd3df11a032fff9b3a32029f49f0fc7c322f556f26ea9ef812d6e43cb21
homepage   : https://matplotlib.org/
license    : Python-2.0
component  : programming.python
summary    : Python plotting library
description: |
    matplotlib strives to produce publication quality 2D graphics for interactive graphing, scientific publishing, user interface development and web application servers targeting multiple user interfaces and hardcopy output formats. There is a ‘pylab’ mode which emulates matlab graphics.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(python3)
    - pkgconfig(tk)
    - pkgconfig(x11)
    - numpy
    - python-certifi
    - python3-tkinter
rundeps    :
    - cycler
    - numpy
    - pyparsing
    - python-dateutil
    - python-kiwisolver
    - python-pillow
    - python-pytz
    - python3-tkinter
setup      : |
    # Use system freetype
    sed -e 's|#system_freetype = False|system_freetype = True|' setup.cfg.template > setup.cfg
build      : |
    export CFLAGS="$CFLAGS -I/usr/include"
    %python3_setup
install    : |
    %python3_install
